# Generated by Django 2.2 on 2019-05-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOR', '0006_blog_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
